sudo: required

language: c

env:
- PKG_NAME=atlasrep
- PKG_NAME=crime
- PKG_NAME=ctbllib
- PKG_NAME=fga
- PKG_NAME=float
- PKG_NAME=fr
- PKG_NAME=gbnp
- PKG_NAME=guarana
- PKG_NAME=hap
- PKG_NAME=hapcryst
- PKG_NAME=happrime
- PKG_NAME=help
- PKG_NAME=idrel
- PKG_NAME=linboxing
- PKG_NAME=loops
- PKG_NAME=lpres
- PKG_NAME=polycyclic
- PKG_NAME=polymaking
- PKG_NAME=profiling
- PKG_NAME=qaos
- PKG_NAME=radiroot
- PKG_NAME=semigroups
- PKG_NAME=tomlib
- PKG_NAME=unipot
- PKG_NAME=wedderga
- PKG_NAME=xmodalg

services:
  - docker

before_install:
- docker pull gapsystem/gap-docker-stable

script:
    - docker version
    - docker run -t gapsystem/gap-docker-stable /bin/sh -c "cd /home/gap/inst/gap-stable-4.8/; sudo wget https://raw.githubusercontent.com/gap-system/gap-docker-pkg-tests/master/testpackage.g; sudo wget https://raw.githubusercontent.com/gap-system/gap-docker-pkg-tests/master/testpackage.sh; sudo chmod u+x testpackage.sh ; sudo ./testpackage.sh ${PKG_NAME}; cat dev/log/*; if [ \`cat dev/log/*.${PKG_NAME} | grep -c '#I  No errors detected while testing'\` != '3' ]; then exit 1; fi;"
